force-app/main/default/objects/Email_Template__mdt/fields/HTML_Email_String__c.field-meta.xml
<CustomField>
    <fullName>HTML_Email_String__c</fullName>
    <label>HTML Email String</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

email-forms/main/default/classes/EmailTemplateFinder.cls
public with sharing class EmailTemplateFinder {
  @AuraEnabled(cacheable=true)
  public static List<Email_Template__mdt> getEmailTemplates() {
    return [
      SELECT Id, MasterLabel, DeveloperName, HTML_Email_String__c
      FROM Email_Template__mdt
    ];
  }

  public static Email_Template__mdt getEmailTemplate(Id templateId) {
    try {
      return [
        SELECT Id, MasterLabel, DeveloperName, HTML_Email_String__c
        FROM Email_Template__mdt
        WHERE Id = :templateId
      ];
    } catch (Exception e) {
      return null;
    }
  }
}