force-app/main/default/objects/Email_Form__c/Email_Form__c.object-meta.xml
<CustomObject>
    <label>Email Form</label>
    <nameField>
        <label>Email Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Email Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Email_Form__c/fields/Email_Template_Metadata_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Template_Metadata_Id__c</fullName>
    <label>Email Template Metadata Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

email-forms/main/default/objects/Email_Form__c/fields/Form_HTML__c.field-meta.xml
<CustomField>
    <fullName>Form_HTML__c</fullName>
    <label>Form HTML</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

email-forms/main/default/objects/Email_Form__c/fields/Form_JSON__c.field-meta.xml
<CustomField>
    <fullName>Form_JSON__c</fullName>
    <label>Form JSON</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Email_Form__c/fields/Intro_Text__c.field-meta.xml
<CustomField>
    <fullName>Intro_Text__c</fullName>
    <label>Intro Text</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

email-forms/main/default/objects/Email_Form__c/fields/Outro_Text__c.field-meta.xml
<CustomField>
    <fullName>Outro_Text__c</fullName>
    <label>Outro Text</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Email_Form__c/fields/Recipient_Email_Field__c.field-meta.xml
<CustomField>
    <fullName>Recipient_Email_Field__c</fullName>
    <label>Recipient Email Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

email-forms/main/default/objects/Email_Form__c/fields/Recipient_Name_Field__c.field-meta.xml
<CustomField>
    <fullName>Recipient_Name_Field__c</fullName>
    <label>Recipient Name Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

email-forms/main/default/objects/Email_Form__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Create</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

email-forms/main/default/objects/Email_Form_Send__c/Email_Form_Send__c.object-meta.xml
<CustomObject>
    <label>Email Form Send</label>
    <nameField>
        <displayFormat>Send-{0000000}</displayFormat>
        <label>Email Form Send Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Form Sends</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Email_Form_Send__c/fields/Email_Form__c.field-meta.xml
<CustomField>
    <fullName>Email_Form__c</fullName>
    <label>Email Form</label>
    <referenceTo>Email_Form__c</referenceTo>
    <relationshipLabel>Email Form Sends</relationshipLabel>
    <relationshipName>Email_Form_Sends</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Test_FormEndpoint.cls
@IsTest
public inherited sharing class Test_FormEndpoint {
  @IsTest
  static void itHandlesUpdateForm() {
    Test.startTest();
    Lead lead = new Lead(
      FirstName = 'Myles',
      Email = 'myles@emergencelabs.io',
      LastName = 'Lead',
      Company = 'Company',
      Description = 'hi there'
    );
    insert lead;
    Email_Form__c form = new Email_Form__c(
      Email_Template_Metadata_Id__c = 'm001k000000BP8A',
      Form_HTML__c = '<form action="{{FORM_ACTION}}" method="get" style=width:100%;text-align:left;margin-top: 10px;><input type="hidden" value="Lead" name="objectApiName"/><input type="hidden" value="{{FORM_ID}}" name="formId"/><button type="submit" style="font-family: Helvetica;box-sizing:border-box;width: 100%;display: blockbackground-color: #345beb;border: none;padding: 10px;color: #fff;font-size: 15px;border-radius: 6px;margin-bottom: 10px;">Submit</button></form>',
      Form_JSON__c = '{"introFields":["Name"],"outroFields":["Description"],"selectedFields":["Status"]}',
      Intro_Text__c = '{{Name}}',
      Object_API_Name__c = 'Lead',
      Outro_Text__c = '{{Description}}',
      Type__c = 'Update',
      Recipient_Email_Field__c = 'Email',
      Recipient_Name_Field__c = 'FirstName'
    );
    insert form;
    FormAPI.EmailSendParams params = new FormAPI.EmailSendParams();
    params.siteUrl = 'https://www.example.com';
    params.formId = form.Id;
    params.recordId = lead.Id;
    params.senderEmailAddress = 'myles@emergencelabs.io';
    params.senderName = 'Myles';
    params.recipientEmailAddress = 'test@example.com';
    params.recipientName = 'Example Name';
    FormAPI.sendEmail(new List<FormAPI.EmailSendParams>{ params });

    Email_Form_Send__c formSend = [SELECT Id FROM Email_Form_Send__c];

    RestRequest request = new RestRequest();
    RestResponse response = new RestResponse();

    request.requestUri =
      'https://cipdev-endpoints.cs195.force.com/services/apexrest/form/' +
      formSend.Id;
    request.httpMethod = 'GET';
    request.addParameter('formId', formSend.Id);
    request.addParameter('objectApiName', 'Lead');
    request.addParameter('recordId', lead.Id);
    request.addParameter('Description', 'hello');
    RestContext.request = request;
    RestContext.response = response;
    FormEndpoint.handleFormSubmit();

    Test.stopTest();
  }

  @IsTest
  static void itHandlesCreateForm() {
    Test.startTest();

    Email_Form__c form = new Email_Form__c(
      Email_Template_Metadata_Id__c = 'm001k000000BP8A',
      Form_HTML__c = '<form action="{{FORM_ACTION}}" method="get" style=width:100%;text-align:left;margin-top: 10px;><input type="hidden" value="Lead" name="objectApiName"/><input type="hidden" value="{{FORM_ID}}" name="formId"/><button type="submit" style="font-family: Helvetica;box-sizing:border-box;width: 100%;display: block;background-color: #345beb;border: none;padding: 10px;color: #fff;font-size: 15px;border-radius: 6px;margin-bottom: 10px;">Submit</button></form>',
      Form_JSON__c = '{"introFields":[],"outroFields":[],"selectedFields":[]}',
      Intro_Text__c = 'hi',
      Object_API_Name__c = 'Lead',
      Outro_Text__c = 'bye',
      Type__c = 'Create'
    );
    insert form;
    FormAPI.EmailSendParams params = new FormAPI.EmailSendParams();
    params.siteUrl = 'https://www.example.com';
    params.formId = form.Id;
    params.senderEmailAddress = 'myles@emergencelabs.io';
    params.senderName = 'Myles';
    params.recipientEmailAddress = 'test@example.com';
    params.recipientName = 'Example Name';
    FormAPI.sendEmail(new List<FormAPI.EmailSendParams>{ params });

    Email_Form_Send__c formSend = [SELECT Id FROM Email_Form_Send__c];

    RestRequest request = new RestRequest();
    RestResponse response = new RestResponse();

    request.requestUri =
      'https://cipdev-endpoints.cs195.force.com/services/apexrest/form/' +
      formSend.Id;
    request.httpMethod = 'GET';
    request.addParameter('formId', formSend.Id);
    request.addParameter('objectApiName', 'Lead');
    RestContext.request = request;
    RestContext.response = response;
    FormEndpoint.handleFormSubmit();

    Test.stopTest();
  }
}