email-forms/main/default/objects/Email_Form__c/Email_Form__c.object-meta.xml
<CustomObject>

    <label>Email Form</label>
    <nameField>
        <label>Email Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Email Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

email-forms/main/default/objects/Email_Form__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Create</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

email-forms/main/default/classes/Test_OrgAPI.cls
@IsTest
public inherited sharing class Test_OrgAPI {
  @IsTest
  static void itGetsObjectsInOrg() {
    Test.startTest();
    List<Map<String, String>> objects = OrgAPI.getObjectsInOrg();
    System.assert(objects.size() > 0);
    Test.stopTest();
  }
  @IsTest
  static void itGetsPicklistOptions() {
    Test.startTest();
    Map<String, List<Map<String, String>>> picklistOptions = OrgAPI.getPicklistOptionsForObject(
      'Email_Form__c'
    );
    System.assert(picklistOptions.get('Type__c').size() > 0);
    Test.stopTest();
  }
}