inbound-email/main/default/objects/Inbound_Email__c/Inbound_Email__c.object-meta.xml
<CustomObject>
    <label>Inbound Email</label>
    <nameField>
        <displayFormat>IN-{0000000}</displayFormat>
        <label>Email Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inbound Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

inbound-email/main/default/objects/Inbound_Email__c/fields/From_Email__c.field-meta.xml
<CustomField>
    <fullName>From_Email__c</fullName>
    <label>From Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

inbound-email/main/default/objects/Inbound_Email__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Inbound Emails</relationshipLabel>
    <relationshipName>Inbound_Emails</relationshipName>
    <type>Lookup</type>
</CustomField>

inbound-email/main/default/objects/Inbound_Email__c/fields/Matched_Multiple_Leads__c.field-meta.xml
<CustomField>
    <fullName>Matched_Multiple_Leads__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Matched Multiple Leads</label>
    <type>Checkbox</type>
</CustomField>

inbound-email/main/default/objects/Inbound_Email__c/fields/To_Email__c.field-meta.xml
<CustomField>
    <fullName>To_Email__c</fullName>
    <label>To Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

inbound-email/main/default/classes/InboundEmailHandler.cls
global with sharing class InboundEmailHandler implements Messaging.InboundEmailHandler {
  global Messaging.InboundEmailResult handleInboundEmail(
    Messaging.InboundEmail email,
    Messaging.InboundEnvelope env
  ) {
    try {
      Messaging.InboundEmail.Header[] headers = email.headers;
      String fromEmail;
      String toEmail;
      for (Messaging.InboundEmail.Header header : headers) {
        if (header.name == 'From') {
          fromEmail = parseFromHeader(header.value);
        } else if (header.Name == 'To') {
          toEmail = parseFromHeader(header.value);
        }
      }
      if (fromEmail == 'forwarding-noreply@google.com') {
        sendBack(email);
      } else {
        System.debug(fromEmail);
        List<Lead> l = [
          SELECT Id
          FROM Lead
          WHERE Email = :fromEmail
          ORDER BY LastModifiedDate
        ];
        if (l.size() > 0) {
          Inbound_Email__c inboundEmailRecord = new Inbound_Email__c(
            From_Email__c = fromEmail,
            Lead__c = l.get(0).Id,
            Matched_Multiple_Leads__c = l.size() > 1,
            HTML_Body__c = email.htmlBody,
            Text_Body__c = email.plainTextBody,
            Subject__c = email.subject,
            To_Email__c = toEmail
          );

          insert inboundEmailRecord;
        }
      }

      return null;
    } catch (Exception e) {
      return null;
    }
  }

  private static String parseFromHeader(String fromHeader) {
    if(fromHeader.indexOf('<') != -1){
      return fromHeader.substring(
        fromHeader.indexOf('<') + 1,
        fromHeader.indexOf('>')
      );
    }
    return fromHeader;
  }

  private static void sendBack(Messaging.InboundEmail email) {
    String subject = email.subject;
    String originEmail = subject.substring(subject.lastIndexOf(' '));
    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
    String[] toAddresses = new List<String>{ originEmail };
    mail.setToAddresses(toAddresses);
    mail.setReplyTo(originEmail);
    mail.setSenderDisplayName('Salesforce Email Service');
    mail.setSubject(subject);
    mail.setPlainTextBody(email.plainTextBody);

    mail.setHtmlBody(email.htmlBody);
    Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{ mail });
  }
}